version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ogs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ogform
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ogformdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ogform -d ogformdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ogs_network

networks:
  ogs_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
